### ISSUE TITLE
large ServerLag

### ISSUE THREAD

**Issue by RedCriterion** [SandedShoes/Weeping-Angels#31]
I'm using:
spongeforge API 7.1.0 v.3406
forge 1.12.2-14.23.4.2756

I'm running a server and recently i've seen large amounts of my resources going towards your mod.

Here's the spark profiling log:
https://sparkprofiler.github.io/?BmytD6Rbd6

and as you can see me.sub.angels.common.entities.EntityQuantumLockBase.func_70071_h_()
is taking 33% of my resources. 

Please fix :) thank you!

**Comment by SandedShoes** [comment]
Hey, yeah this has been a issue I've been investigating ever since I added the whole "A angel freezes when it sees another one" 

To further look into this, can I look into your Weeping angels config? I feel like I did something silly

**Comment by RedCriterion** [comment]
Ofcourse !

[weeping-angels.txt](https://github.com/SandedShoes/Weeping-Angels/files/2307981/weeping-angels.txt)

**Comment by SandedShoes** [comment]
```MD
   # Note: This a list of dimensions that angels should NOT teleport you to.
        I:notAllowedDimensions <
            TROPICS
            DIM-343800852
            343800852
         >``` Unrelated to the issue at hand, but TROPICS won't fix anything here, only dimenion interger numbers for here

That aside, I'm just compiling a fix for you

Could you also tell me how you do your profiling? I would love to know in order to profile my mods in future

But if you could profile the next release I'm about to put out, that would be great!

**Comment by SandedShoes** [comment]
Considering Curse Forge can take awhile to allow a file to be allowed on their site
I sugget you try with this jar until they publish it: https://github.com/SandedShoes/Weeping-Angels/releases/tag/19.1

Thank you for reporting your issue and please do let me know how this fix goes <3

**Comment by RedCriterion** [comment]
to profile i use the spark profiling mod:
https://ore.spongepowered.org/Luck/spark

You run /profiler start whenever you experience lags or the perfomance could be better and shortly after you use /profiler stop.

I will take a look how it goes with your fix :) thank you!

**Comment by SandedShoes** [comment]
Anytime!

**Comment by nictogen** [comment]
Should be easy to fix if you switch to an active rather than a passive form of detection (Like I did when I did the teleporting stuff)

i.e. only check if an angel is quantum locked by another when that angel wants to move, instead of every single tick

**Comment by SandedShoes** [comment]
It's been moved to another branch if you want to take a look
I would myself but sorts occupied with stuff today

**Comment by SandedShoes** [comment]
@RedCriterion Hey, any update on this?

**Comment by RedCriterion** [comment]
Hey, not experiencing issues, but what i thought would be a great addition
is the ignorance of players in invisible state.

Sub <notifications@github.com> schrieb am So., 26. Aug. 2018, 11:56:

**Comment by SandedShoes** [comment]
Ah that's great to here!
I assume you mean when players are in vanish and such?

**Comment by RedCriterion** [comment]
yes, or in creative, because either they follow me or they wont move
because i see them.

Sub <notifications@github.com> schrieb am So., 26. Aug. 2018, 13:57:

**Comment by SandedShoes** [comment]
Invisible sure, creative I'm iffy on
I can make a config option I guess, off by default

**Comment by RedCriterion** [comment]
normal mobs also dont chase you in creative, so i dont quite see why it's
iffy :D

Sub <notifications@github.com> schrieb am So., 26. Aug. 2018, 14:01:

**Comment by SandedShoes** [comment]
OH, you just mean the targeting?

**Comment by SandedShoes** [comment]
All sorted :)
