### ISSUE TITLE
[Enhancement] Better Vivecraft Compat

### ISSUE THREAD

**Issue by shadowbolt79** [SandedShoes/Weeping-Angels#33]
Let me just say this first - this mod works well in vivecraft. [https://github.com/jrbudda/Vivecraft_112]

However - The looking at an angel is done by your main hand rather than via your actual head look. This is mostly ok as when you're pointing forward most of the time when you're moving, but when you're mining you're swinging that main hand around (if you use roomscale mining, that is). So if you're mining and an angel sneaks up on you, turning to look at it won't stop it until you bring your hand in the same direction.

That and it allows you to turn your head and look where you're going instead of at the angel when you're trying to back away.

I don't expect you to do this anytime soon, or possibly at all, but if you can, that'll make this mod that much better in my books.

**Comment by SandedShoes** [comment]
Got any footage of said bug?

**Comment by shadowbolt79** [comment]
https://imgur.com/a/lDNSVPH

All I'm doing is flicking my hand over my shoulder to get it to move. In the second image I'm able to move away from the angel just because my main hand is pointing at its general location.

They've separated the player's selection target and camera look. On servers it would probably only be able to tell properly if it has the Vivecraft Forge Extensions mod installed, since that is capable of receiving the proper look target. I believe they've made fix code for enderman with that in mind.

**Comment by SandedShoes** [comment]
Thank you, I'm gonna go take a look into this now!

**Comment by shadowbolt79** [comment]
Interestingly enough, Botania's Assembly Halo follows the head movement instead of the hand for selection. Unsure if something useful could be gleamed from there.

Also, thank you kindly for taking a look! This bug is a lot more minor than Astral Sorcery's Observatory which spins you around at mach 5.

**Comment by SandedShoes** [comment]
I found a lead as to what to do for compatiblity, shouldn't take me that long
Looks like I have to replace my Vec3D with their one if it's installed
